### ISSUE TITLE
concurrency exception

### ISSUE THREAD

**Issue by NicoKiaru** [imglib/imglib2-cache#15]
I sometime get a `java.util.concurrent.ExecutionException` when I get several spimsources in parallel in
https://github.com/imglib/imglib2-cache/blob/master/src/main/java/net/imglib2/cache/util/CacheAsUncheckedCacheAdapter.java

The error message is:

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Hook previously registered
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:45)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:230)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:222)
```

**Comment by tpietzsch** [comment]
@NicoKiaru I hope this is fixed by https://github.com/imglib/imglib2-cache/commit/0cb00d72d24cbb8e2b54cbbaabb79135803db56f
